FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
RUN echo '<html><body style="margin:0;display:flex;justify-content:center;align-items:center;height:100vh;background:linear-gradient(135deg,#ffdde1,#ee9ca7);font-family:sans-serif;text-align:center;"><h1 style="color:#fff;font-size:2em;">💌 Hey Angel 💫<br><br>Just a small note to say — I love you more every single day ❤️<br><br>You’re my world, my peace, my forever 🌹<br><br>— From your Banti Bava 💕</h1></body></html>' > /usr/share/nginx/html/index.html
