FROM nginx
RUN rm -rf /usr/share/nginx/html/index.html
RUN echo '<html><body style="margin:0;display:flex;justify-content:center;align-items:center;height:100vh;"><h1>Hi, I am from APP-2</h1></body></html>' > /usr/share/nginx/html/index.html
